"""Node transport synchronization without access to host runtime or registry credentials."""
import asyncio
from datetime import datetime, timezone, timedelta
import json
from pathlib import Path
import tomllib
from unittest.mock import AsyncMock, patch
import pytest
from fastapi import HTTPException
from backend.worker.registry_node import apply_transport, render_hosts, transport_hash, MARKER
from backend.tests.test_publication import FakeController

HOST = 'registry.example.test:30500'


def runtime_config(path, version=2):
    plugin = 'io.containerd.grpc.v1.cri' if version == 2 else 'io.containerd.cri.v1.images'
    path.write_text(f'version = {version}\n[plugins."{plugin}".registry]\n'
                    'config_path = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d"\n')


@pytest.mark.parametrize('version', [2, 3])
def test_http_and_https_reload_preserve_ca_and_survive_k3s_regeneration(tmp_path, version):
    config = tmp_path / 'config.toml'; runtime_config(config, version)
    source = tmp_path / 'original'; source.mkdir()
    target = tmp_path / 'managed'; target.mkdir()
    original = f'# File generated by k3s. DO NOT EDIT.\nserver = "https://{HOST}/v2"\nca = ["/etc/registry-ca.crt"]\n[host."http://{HOST}/v2"]\ncapabilities = ["pull", "resolve"]\n'
    (source / 'hosts.toml').write_text(original)
    apply_transport(target, HOST, True, config, source)
    actual = tomllib.loads((target / 'hosts.toml').read_text())
    assert actual['server'] == f'http://{HOST}/v2'
    assert actual['ca'] == ['/etc/registry-ca.crt']
    assert all(key.startswith('http://') for key in actual['host'])
    assert (source / 'hosts.toml').read_text() == original
    apply_transport(target, HOST, False, config, source)
    assert tomllib.loads((target / 'hosts.toml').read_text())['server'] == f'https://{HOST}/v2'
    # k3s regenerates only its colon directory; the preferred underscore directory remains managed.
    (source / 'hosts.toml').write_text(original)
    apply_transport(target, HOST, True, config, source)
    assert (target / 'hosts.toml').read_text().startswith(MARKER)
    assert tomllib.loads((target / 'hosts.toml').read_text())['server'].startswith('http://')


def test_unsupported_config_and_symlinks_are_rejected(tmp_path):
    config = tmp_path / 'config.toml'; config.write_text('version=2')
    with pytest.raises(ValueError):
        apply_transport(tmp_path, HOST, True, config)
    runtime_config(config)
    elsewhere = tmp_path / 'private'; elsewhere.write_text('unchanged')
    (tmp_path / 'hosts.toml').symlink_to(elsewhere)
    with pytest.raises(ValueError):
        apply_transport(tmp_path, HOST, True, config)
    assert elsewhere.read_text() == 'unchanged'
    with pytest.raises(ValueError):
        render_hosts('', '../docker.io', True)


def test_publication_applies_ui_transport_not_ansible_default():
    async def check():
        c = FakeController(registry_http=False)
        await c.ensure_transport({'kind': 'private', 'host': HOST, 'http': True})
        assert json.loads(c.store[(False, 'configmaps', 'registry-pull-transport')]['data']['transport']) == {
            'host': HOST, 'http': True}
        with pytest.raises(HTTPException, match='422'):
            await c.ensure_transport({'kind': 'private', 'host': 'other.test:30500', 'http': True})
        await c.ensure_transport({'kind': 'artifact', 'host': 'unused'})
    asyncio.run(check())


@pytest.mark.parametrize('failure', ['missing', 'stale', 'wrong_hash', 'missing_node'])
def test_publication_waits_for_every_node_to_apply_exact_transport(failure):
    async def check():
        c = FakeController()
        original = c.kube
        async def kube(method, resource, name='', **kwargs):
            if resource == 'daemonsets':
                return None if failure == 'missing' else {'status': {'desiredNumberScheduled': 2}}
            if resource == 'pods':
                return {'items': [{'metadata': {}, 'spec': {'nodeName': node}} for node in ('node-1', 'node-2')]}
            if resource == 'leases':
                stamp = datetime.now(timezone.utc) - timedelta(seconds=60 if failure == 'stale' else 0)
                return {'items': [{'metadata': {'annotations': {'node': node,
                    'transport-hash': 'wrong' if failure == 'wrong_hash' else transport_hash(HOST, True)}},
                    'spec': {'renewTime': stamp.isoformat()}} for node in
                    (('node-1',) if failure == 'missing_node' else ('node-1', 'node-2'))]}
            return await original(method, resource, name, **kwargs)
        c.kube = kube
        with patch('backend.worker.publication_controller.asyncio.sleep', new=AsyncMock()):
            with pytest.raises(HTTPException) as error:
                await c.ensure_transport({'kind': 'private', 'host': HOST, 'http': True})
        assert error.value.status_code == 422
    asyncio.run(check())


def test_missing_node_sync_does_not_replace_running_publication():
    from backend.tests.test_publication import source, BUILD, SHA, PROJECT, TENANT
    from backend.worker.publication_controller import PublishInput
    async def check():
        c = FakeController()
        build = await c.submit(BUILD, source())
        build.update(status='succeeded', digest=SHA)
        await c.record('build-' + BUILD, build)
        name = 'published-' + PROJECT
        previous = {'status': 'running', 'current': {'build_id': BUILD}}
        await c.record(name, previous)
        original = c.kube
        async def kube(method, resource, name='', **kwargs):
            if resource == 'daemonsets':
                return None
            return await original(method, resource, name, **kwargs)
        c.kube = kube
        with pytest.raises(HTTPException) as error:
            await c.publish(PROJECT, PublishInput(tenant_id=TENANT, build_id=BUILD,
                image=build['image'].rsplit(':', 1)[0] + '@' + SHA,
                app_origin='https://koyorina.test', forward_secret='f' * 40))
        assert error.value.status_code == 422
        assert await c.record(name) == previous
        assert (True, 'deployments', name) not in c.store
        assert (True, 'persistentvolumeclaims', name + '-data') not in c.store
    asyncio.run(check())


def test_http_selection_with_default_host_also_applies_to_build_push():
    from backend.tests.test_publication import source, BUILD
    from backend.domain.system_registry import RegistrySelection
    async def check():
        c = FakeController(registry_http=False)
        payload = source().model_copy(update={'registry': RegistrySelection(http=True)})
        build = await c.submit(BUILD, payload)
        await c.start_build(build)
        pod = c.store[(False, 'jobs', 'build-' + BUILD)]['spec']['template']['spec']
        env = {entry['name']: entry['value'] for entry in pod['containers'][0]['env']}
        assert env['REGISTRY_HTTP'] == 'true'
        assert env['REGISTRY_ENDPOINT'] == HOST
    asyncio.run(check())


def test_node_sync_uses_rotated_service_account_token(tmp_path, monkeypatch):
    import backend.worker.registry_node as node_module
    token = tmp_path / 'token'; token.write_text('first-token')
    ready = tmp_path / 'ready'
    actual_path = Path
    def local_path(value):
        return token if value.endswith('/serviceaccount/token') else ready if value == '/tmp/registry-node-ready' else actual_path(value)
    monkeypatch.setattr(node_module, 'Path', local_path)
    monkeypatch.setattr(node_module.ssl, 'create_default_context', lambda **kwargs: None)
    monkeypatch.setattr(node_module, 'apply_transport', lambda *args: None)
    for key, value in {'REGISTRY_HOST': HOST, 'POD_NAMESPACE': 'koyorina-build', 'NODE_NAME': 'node-1'}.items():
        monkeypatch.setenv(key, value)
    submitted_tokens = []
    class Response:
        def raise_for_status(self): pass
        def json(self):
            return {'data': {'transport': json.dumps({'host': HOST, 'http': True})}}
    class Client:
        def __init__(self, **kwargs): self.headers = {}
        async def __aenter__(self): return self
        async def __aexit__(self, *args): pass
        async def get(self, *args): return Response()
        async def patch(self, *args, **kwargs):
            submitted_tokens.append(self.headers['Authorization'])
            return Response()
    monkeypatch.setattr(node_module.httpx, 'AsyncClient', Client)
    turns = 0
    async def sleep(seconds):
        nonlocal turns
        turns += 1
        if turns == 2:
            raise asyncio.CancelledError
        token.write_text('rotated-token')
    monkeypatch.setattr(node_module.asyncio, 'sleep', sleep)
    async def check():
        with pytest.raises(asyncio.CancelledError):
            await node_module.run()
    asyncio.run(check())
    assert submitted_tokens == ['Bearer first-token', 'Bearer rotated-token']
